name: Test

on: 
  push:
    branches:
      - '**'
  pull_request:
      types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Action
      uses: ./
      with:
        mainBranch: master
        prereleaseBranches: alpha,beta,rc
